### ISSUE TITLE
コマンドのdocumentを作ろう

### ISSUE THREAD

**Issue by velvelhype** [hyudai28/ft_irc#11]
コマンドのドキュメント作ります！
docs/commands.txt みたいな感じ

**Comment by velvelhype** [comment]
commandファイルを一個一個作っちゃって、上に説明を入れていく
そのあと一覧作ってもいいね

**Comment by hyudai28** [comment]
1.serverquery
2.servicequery
docs 担当hyudai

**Comment by hyudai28** [comment]
それ以外kamori

**Comment by velvelhype** [comment]
とりあえずは全部完了！
