### ISSUE TITLE
[NEW] make_ircdブランチの実装について

### ISSUE THREAD

**Issue by fujishit** [hyudai28/ft_irc#15]
[NEW] マージ前のmake_ircdブランチの実装について
------------------------------------
make_ircdブランチにircサーバーに最低限必要な実装を作ってるので、
bircdに元々あった実装や、必須の実装とそのイメージを大体まとめておく。
Serverクラスに実装する。

実装予定
------------------------------------

- [x] ソケットの作成
- socket()を利用しソケットを作成する。

- [x] ソケットの設定
- bind()を利用しソケットの設定を行う。
- setsockopt(), fcntl()も使えそう。
- [x] ソケットを接続待ち状態にする。
- listen()を利用し、接続待ち状態にする。
- [x] 接続する。
- accept()を利用し、connect()を送ってきたクライアントと実際に通信する。
- [x] 送信されたコマンドの受信
- poll()やselect()を利用し、fdを監視し受信する。

これらを一人のユーザーに対して出来るようになったら、make_ircdをマージしUserクラスを新規実装する。

Labels
------------------------------------
new

Milestone
------------------------------------
10/07
 

Assignee
------------------------------------
fujishit

関連するissue
------------------------------------

資料
------------------------------------

**Comment by hyudai28** [comment]
merge確認したので終了。新しい問題は別でissueを建てること
