### ISSUE TITLE
[SURVEY]make_ircdに対してirssiが接続できない

### ISSUE THREAD

**Issue by hyudai28** [hyudai28/ft_irc#21]
[SURVEY]xxx
------------------------------------
make_ircdで構築したサーバーにirssiから接続しようとしても失敗する

調査項目
------------------------------------

1. sslのhandshakeが失敗している理由を突き止める
2. make_ircdでnicknameなどの情報が表示されるようにする

### 問題の内容・実装箇所の仕様
1. SSLのhandshakeが失敗している（呼び出し方の問題？）
3. その結果コネクションロスト

make_ircdの出力を見る限りはnew connectionがあるので接続は問題なさそう。
SSL/TSLで接続してないから失敗してるかもしれない。

irssi_log
```
21:22 -!- Irssi: Looking up 127.0.0.1
21:22 -!- Irssi: Connecting to 127.0.0.1 [127.0.0.1] port 6667
21:22 -!- Irssi: warning SSL handshake failed: unexpected message
21:22 -!- Irssi: Connection lost to 127.0.0.1
```

Labels
------------------------------------

### bug
バグ報告をするときに使う。  
→ 修正したらクローズする

### duplicate
過去に報告されているIssueと重複しているときに使う。  
※ 報告者は使わない  
→ 重複先のIssueにリンクしてクローズする

### new
機能追加の要望や改善してほしいときに使う。  
→ 実装したらクローズする

### invalid
Issueの内容が間違いであるときに使う。仕様通り。
※ 報告者は使わない  
→ 対処しない理由を書いてクローズする

### question
質問したいときに使う。  
→ 質問・議論の答えがでたらクローズする

### wontfix
認知しているけど対処しないバグのときに使う。  
※ 報告者は使わない  
→ 対処しない理由を書いてクローズする

Milestone
------------------------------------

Assignee
------------------------------------

関連するissue
------------------------------------

資料
------------------------------------

**Comment by hyudai28** [comment]
TLSのハンドシェイクを行おうとしてサーバー側で応答がないので失敗してる気がする。
TLSの接続を行うためのチケットを切る。


Limechatはおそらくhandshakeリクエストを送って、その返答がなければTLSなしで通信開始してるかもしれない。

**Comment by velvelhype** [comment]
考えられるアプローチ：
execrateのコードリーディング、もしくはirssiのsslの設定を変更する
