### ISSUE TITLE
[REFACTOR]Server::loop()意味不明問題

### ISSUE THREAD

**Issue by fujishit** [hyudai28/ft_irc#28]
[REFACTOR]Server::loop()意味不明問題
------------------------------------

Server::loop()がごちゃってて可読性保守性共に死んでるので、改善案のメモと募集。

Comment
------------------------------------
基本的に全部に適用できるのでアイデア集みたいなノリもある。
みんなでよりよいコードを書くためのアイデアだせたらいいな～～

### 問題の内容・実装箇所 

とにかくコードがつめつめで、ごちゃごちゃしてるので改善する。

### アイデア

- 関数に分ける。必要であればファイルごと分ける。
- コメントを書く。これは何をしているっていうのを区切りごとに書いておくといいよね。
- そもそも責任を持つ場所があってるかを考える。不適切な場所にコードがあると、ごちゃごちゃになるので困る。
- ifのかっこつめてもいいんじゃないって少し思ってる。これは宗教だけどすっきりはする。

### Server::loop()をどうするかの例

```
void	Server::loop()
{
	//pollとエラー処理
	waitEvent();
	if (this->poll_fds[0].revents == POLLIN)
	{
		//ユーザーに対しacceptを行い、Server::user[n]を追加する。
		acceptUser();
	} else {
		/* 少し悩み中、やることはreceiveなんだけど、全部回さなきゃいけない。関数にするほど？ */
		for (std::vector<pollfd>::iterator it = this->poll_fds.begin(); it != this->poll_fds.end(); ++it) {
			if ((*it).revents == POLLIN) {
				this->users[(*it).fd]->receive();
			}
		}
	}
	//ユーザーが退出していないか、退出していればそれの処理。
	checkLeaveUser();
}
```

多分これぐらいスッキリすればコメントなくても、あるいはない方がスッキリ見えると思う。
できれば関数の上にやることは書きたいから、コード中にはあんまり書かない(行数が増えない)ことが美徳じゃないかと考えてる。

Labels
------------------------------------

refactor

Milestone
------------------------------------
10/18 やりたいって思った

Assignee
------------------------------------
fujishita-san

関連するissue
------------------------------------
コミットメッセージに以下のフォーマットで記述すれば、自動的に該当Issue（#12）がCloseされる。

* fix #xx
* fixes #xx
* fixed #xx

資料
------------------------------------

**Comment by hyudai28** [comment]
acceptで一回止めて、止めてる間に２人アクセスしてみる。
情報は消えるのか、二人とも受け入れられるのか

**Comment by hyudai28** [comment]
これって今動くんだっけ？

**Comment by fujishit** [comment]
> これって今動くんだっけ？

これがどれか分からないけど、pushしたやつは全部動くと思う

**Comment by hyudai28** [comment]
あざっす、仕事終わって家帰ったら確認するわ

**Comment by hyudai28** [comment]
ちょっと帰ってからパース書きたいから付き合ってほしい21:00-23:00

**Comment by fujishit** [comment]
> 

りょ
