### ISSUE TITLE
[CRASH]ft_ircが一定の条件下でクラッシュする。

### ISSUE THREAD

**Issue by hyudai28** [hyudai28/ft_irc#37]
[CRASH]ft_ircが一定の条件下でクラッシュする。
------------------------------------

調査項目
------------------------------------
1. PRをチェックしてる時にクラッシュしたので状況報告
> irssiで接続し、チャンネルを作成し１文字以上情報を発信、その後放置すると以下のメッセージを残してクラッシュ
`terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 2) >= this->size() (which is 1)
zsh: abort      ./ft_irc`

### 問題の内容・実装箇所の仕様

Labels
------------------------------------

### bug
バグ報告をするときに使う。  
→ 修正したらクローズする

### duplicate
過去に報告されているIssueと重複しているときに使う。  
※ 報告者は使わない  
→ 重複先のIssueにリンクしてクローズする

### new
機能追加の要望や改善してほしいときに使う。  
→ 実装したらクローズする

### invalid
Issueの内容が間違いであるときに使う。仕様通り。
※ 報告者は使わない  
→ 対処しない理由を書いてクローズする

### question
質問したいときに使う。  
→ 質問・議論の答えがでたらクローズする

### wontfix
認知しているけど対処しないバグのときに使う。  
※ 報告者は使わない  
→ 対処しない理由を書いてクローズする

Milestone
------------------------------------

Assignee
------------------------------------

関連するissue
------------------------------------

資料
------------------------------------

**Comment by hyudai28** [comment]
一回壊れたやつを再度使おうとするとconnectした時点でクラッシュ

**Comment by velvelhype** [comment]
調査しといて
std::coutコメントでどこでクラッシュしてるのか突き止めて

**Comment by hyudai28** [comment]
ok,ちょっと時間もらうわ

**Comment by hyudai28** [comment]
定期的にNICKが送られてきている。
既にNICKが存在するときに再度同じユーザーがNICKを送るとクラッシュしそう

**Comment by hyudai28** [comment]
```
(base) DESKTOP-OBFCQ61% ./ft_irc 
server start
new connection -> [4]
=MSG RECEIVED======
CAP LS
NICK hyudai
USER hyudai hyudai localhost :hyudai

===================
hyudai
USER

hyudai

NICK called
capUser done (done nothing actually)

=MSG RECEIVED======
MODE * +i

===================
=MSG RECEIVED======
WHOIS hyudai

===================
=MSG RECEIVED======
PING localhost

===================
hello
disconnect: 4
=MSG RECEIVED======

===================
no cmdsnew connection -> [4]
=MSG RECEIVED======
CAP LS
NICK hyudai
USER hyudai hyudai localhost :hyudai

===================
hyudai
USER

hyudai

NICK called
capUser done (done nothing actually)

=MSG RECEIVED======
MODE * +i

===================
=MSG RECEIVED======
WHOIS hyudai

===================
=MSG RECEIVED======
PING localhost

===================
^C
```

**Comment by hyudai28** [comment]
５分に一回メッセージを送ってる
