### ISSUE TITLE
まずは送られてきているコマンドの解釈、保存がしたい〜〜〜〜

### ISSUE THREAD

**Issue by velvelhype** [hyudai28/ft_irc#9]
™•¶™•【£】¶•【™】¶¡™－¡－™】【¢§¶•£】™£－

どういう形で保存されてるわけ〜〜？？？？
調べなければ〜〜
ただのストリングのリストでいいの〜〜〜？？？？？？

™•¶™•【£】¶•【™】¶¡™－¡－™】【¢§¶•£】™£－

**Comment by hyudai28** [comment]
#10 に移動
